### ISSUE TITLE
Walls - HWAitW

### ISSUE THREAD

**Issue by revilowaldow** [TheGiddyLimit/plutonium-scenes#142]
Add walls for maps in `HWAitW`

Should be 11, maps need setting up + grid data in advance

**Comment by revilowaldow** [comment]
![Image](https://github.com/TheGiddyLimit/plutonium-scenes/assets/52298102/e3cf6de5-b166-4c90-9259-501f8c4a54f2)

**Comment by revilowaldow** [comment]
- [ ] Fig. 1.1: Winnowing Reach
- [ ] Fig. 1.2: Mokkden Caverns
- [ ] Fig. 1.2: Mokkden Caverns (Player Version)
- [ ] Fig. 1.3: Susan's Hut
- [ ] Fig. 1.3: Susan's Hut (Player Version)
- [ ] Fig. 2.1: Alderheart
- [ ] Fig. 2.2: Eliza's Emporium
- [ ] Fig. 2.3: Bandit Camp
- [ ] Fig. 2.3: Bandit Camp (Player Version)
- [ ] Fig. 2.4: Inner Keep
- [ ] Fig. 2.4: Inner Keep (Player Version)
- [ ] Fig. 4.1: Avium
- [ ] Fig. 4.2: Secret Laboratory
- [ ] Fig. 4.2: Secret Laboratory (Player Version)
- [ ] Fig. 5.1: Final Battle with the Aspect
- [ ] Fig. 5.1: Final Battle with the Aspect (Player Version)

**Comment by revilowaldow** [comment]
This one's def in need of dedicated player walls. All sorts of funky stuff going on like significant crops, 90° rotations etc.

**Comment by revilowaldow** [comment]
Rotate walls 90°, taken from Foundry discord https://discord.com/channels/170995199584108546/699750150674972743/1153310497765081180
```js
let centerPoint = canvas.walls.controlled.reduce((acc, wall) => {
    let wallX = wall.document.c[0];
    let wallY = wall.document.c[1];
    acc.x += wallX;
    acc.y += wallY;
    return acc;
},{x: 0, y:0})
centerPoint.x = centerPoint.x / canvas.walls.controlled.length;
centerPoint.y = centerPoint.y / canvas.walls.controlled.length;
const walls = canvas.walls.controlled.map(wall => {
  let w = duplicate(wall.document);
  const mid_offset_0 = w.c[0] - centerPoint.x;
  const mid_offset_1 = w.c[1] - centerPoint.y;
  const mid_offset_2 = w.c[2] - centerPoint.x;
  const mid_offset_3 = w.c[3] - centerPoint.y;
  w.c[0] = centerPoint.x - mid_offset_1;
  w.c[1] = centerPoint.y + mid_offset_0;
  w.c[2] = centerPoint.x - mid_offset_3;
  w.c[3] = centerPoint.y + mid_offset_2;
  return {_id: w._id, c: w.c};
});
canvas.scene.updateEmbeddedDocuments("Wall", walls);
```

**Comment by TheGiddyLimit** [comment]
interesting that they use the first point of the wall to calculate the center, rather than e.g. the midpoint of the wall

wonder if it works any better if you swap that first statement out for:

```js
let centerPoint = canvas.walls.controlled.reduce((acc, wall) => {
	const [x0, y0, x1, y1] = wall.document.c;
	let wallX = x0 + ((x1 - x0) / 2);
	let wallY = y0  + ((y1 - y0) / 2);
	acc.x += wallX;
	acc.y += wallY;
	return acc;
},{x: 0, y:0})
```

not that I imagine it matters for this use-case
