### ISSUE TITLE
Walls - LLK

### ISSUE THREAD

**Issue by TheGiddyLimit** [TheGiddyLimit/plutonium-scenes#17]
Add walls for maps in `LLK`
- [ ] Daoine Gloine
- [ ] Daoine Gloine (Player Version)
- [ ] Map 1: Umberlee's Maw
- [ ] Map 1: Umberlee's Maw (Player Version)
- [ ] Monastery of the Distressed Body
- [ ] Monastery of the Distressed Body (Player Version)

**Comment by revilowaldow** [comment]
No maps in `LLK` require walls
