### ISSUE TITLE
Walls - WDMM

### ISSUE THREAD

**Issue by TheGiddyLimit** [TheGiddyLimit/plutonium-scenes#18]
Add walls for maps in `WDMM`

**Comment by revilowaldow** [comment]
Should you choose to use it:
- [ ] Map 1
- [ ] Map 1 (Player Version)
- [ ] Map 2
- [ ] Map 2 (Player Version)
- [ ] Map 3
- [ ] Map 3 (Player Version)
- [ ] Map 4
- [ ] Map 4 (Player Version)
- [ ] Map 5
- [ ] Map 5 (Player Version)
- [ ] Map 6
- [ ] Map 6 (Player Version)
- [ ] Map 7
- [ ] Map 7 (Player Version)
- [ ] Map 8
- [ ] Map 8 (Player Version)
- [ ] Map 9
- [ ] Map 9 (Player Version)
- [ ] Map 10
- [ ] Map 10 (Player Version)
- [ ] Map 11
- [ ] Map 11 (Player Version)
- [ ] Map 12
- [ ] Map 12 (Player Version)
- [ ] Map 13
- [ ] Map 13 (Player Version)
- [ ] Map 14
- [ ] Map 14 (Player Version)
- [ ] Map 15
- [ ] Map 15 (Player Version)
- [ ] Map 16
- [ ] Map 16 (Player Version)
- [ ] Map 17
- [ ] Map 17 (Player Version)
- [ ] Map 18
- [ ] Map 18 (Player Version)
- [ ] Map 19
- [ ] Map 19 (Player Version)
- [ ] Map 20
- [ ] Map 20 (Player Version)
- [ ] Map 21
- [ ] Map 21 (Player Version)
- [ ] Map 22
- [ ] Map 22 (Player Version)
- [ ] Map 23
- [ ] Map 23 (Player Version)
- [ ] Map 24
- [ ] Map 24 (Player Version)
- [ ] Map 25
- [ ] Map 25 (Player Version)
- [ ] Map 26
- [ ] Map 26 (Player Version)
