### ISSUE TITLE
Walls - GoS

### ISSUE THREAD

**Issue by TheGiddyLimit** [TheGiddyLimit/plutonium-scenes#19]
Add walls for maps in `GoS`

**Comment by revilowaldow** [comment]
- [ ] Map 1.1: Village of Saltmarsh
- [ ] Map 1.1: Village of Saltmarsh (Player Version)
- [ ] Map 1.2: The Saltmarsh Environs
- [ ] Map 1.2: The Saltmarsh Environs (Player Version)
- [ ] Map 2.1: Haunted House
- [ ] Map 2.1: Haunted House (Player Version)
- [ ] Map 2.2: Haunted House Cellar and Caverns
- [ ] Map 2.2: Haunted House Cellar and Caverns (Player Version)
- [ ] Map 2.3: Sea Ghost
- [ ] Map 2.3: Sea Ghost (Player Version)
- [ ] Map 3.1: Lizardfolk Lair
- [ ] Map 3.1: Lizardfolk Lair (Player Version)
- [ ] Map 4.1: Emperor of the Waves
- [ ] Map 4.1: Emperor of the Waves (Player Version)
- [ ] Map 5.1: Abbey Isle
- [ ] Map 5.1: Abbey Isle (Player Version)
- [ ] Map 5.2: Skull Dunes
- [ ] Map 5.2: Skull Dunes (Player Version)
- [ ] Map 5.3: Abbey Ruins
- [ ] Map 5.3: Abbey Ruins (Player Version)
- [ ] Map 6.1: Sahuagin Lair Level 1
- [ ] Map 6.1: Sahuagin Lair Level 1 (Player Version)
- [ ] Map 6.2: Sahuagin Lair Level 2
- [ ] Map 6.2: Sahuagin Lair Level 2 (Player Version)
- [ ] Map 6.3: Sahuagin Lair Level 3
- [ ] Map 6.3: Sahuagin Lair Level 3 (Player Version)
- [ ] Map 7.1: Firewatch Island
- [ ] Map 7.1: Firewatch Island (Player Version)
- [ ] Map 7.2: Hermitage First Floor
- [ ] Map 7.2: Hermitage First Floor (Player Version)
- [ ] Map 7.3: Hermitage Second Floor
- [ ] Map 7.3: Hermitage Second Floor (Player Version)
- [ ] Map 7.4: Hermitage Upper Floors and Cellar
- [ ] Map 7.4: Hermitage Upper Floors and Cellar (Player Version)
- [ ] Map 7.5: The Pit of Hatred
- [ ] Map 7.5: The Pit of Hatred (Player Version)
- [ ] Map 8.1: The Styes
- [ ] Map 8.1: The Styes (Player Version)
- [ ] Map 8.2: Mr Dory's Warehouse
- [ ] Map 8.2: Mr Dory's Warehouse (Player Version)
- [ ] Map 8.3: Temple of Tharizdun
- [ ] Map 8.3: Temple of Tharizdun (Player Version)
- [ ] Map 8.4: Landgrave's Folly
- [ ] Map 8.4: Landgrave's Folly (Player Version)
- [ ] Map A.5: Cove Reef
- [ ] Map A.5: Cove Reef (Player Version)
- [ ] Map A.6: Wreck of the Marshal
- [ ] Map A.6: Wreck of the Marshal (Player Version)
- [ ] Map A.7: Warthalkeel Ruins
- [ ] Map A.7: Warthalkeel Ruins (Player Version)
