### ISSUE TITLE
Walls - OotA

### ISSUE THREAD

**Issue by TheGiddyLimit** [TheGiddyLimit/plutonium-scenes#4]
Add walls for maps in `OotA`
- [x] Map 1.1: Velkynvelve
- [ ] Map 1.1: Velkynvelve (Player Version)
- [x] Map 13.1: Troglodyte Lair
- [ ] Map 13.1: Troglodyte Lair (Player Version)
- [x] Map 13.2: The Worm Nursery
- [ ] Map 13.2: The Worm Nursery (Player Version)
- [ ] Map 15.1: Menzoberranzan
- [ ] Map 2.1: The Underdark
- [x] Map 2.2: The Hook Horror Lair
- [ ] Map 2.2: The Hook Horror Lair (Player Version)
- [x] Map 2.3: The Oozing Temple
- [ ] Map 2.3: The Oozing Temple (Player Version)
- [x] Map 2.4: The Lost Tomb
- [ ] Map 2.4: The Lost Tomb (Player Version)
- [x] Map 3.1: Sloobludop
- [ ] Map 3.1: Sloobludop (Player Version)
- [ ] Map 4.1: Gracklstugh
- [ ] Map 4.1: Gracklstugh (Player Version)
- [x] Map 4.2: Gracklstugh—The Whorlstone Tunnels
- [ ] Map 4.2: Gracklstugh—The Whorlstone Tunnels (Player Version)
- [x] Map 4.3: Lair of the Spider King
- [x] Map 4.4: Gray Ghost Garden
- [x] Map 4.5: Cultist Pens
- [x] Map 4.6: Cultist Hideout
- [x] Map 4.7: Obelisk Chamber
- [x] Map 5.1: Neverlight Grove
- [ ] Map 5.1: Neverlight Grove (Player Version)
- [ ] Map 6.1: Blingdenstone
- [ ] Map 6.1: Blingdenstone (Player Version)
- [ ] Map 6.2: Outer Blingdenstone
- [ ] Map 6.3: Inner Blingdenstone
- [ ] Map 6.4: Rockblight
- [ ] Map 6.5: Goldwhisker Warrens
- [ ] Map 6.6: The Pudding Court
- [x] Map 9.1: Mantol-Derith
- [ ] Map 9.1: Mantol-Derith (Player Version)

**Comment by revilowaldow** [comment]
Though caverns I've decided that the below maps are too low resolution and count as over-world maps (i.e. no walls):
DMs should stage fights in a generic cave map, similarly to how they would use a generic alley map in a surface town.

- Gracklstugh
- Blingdenstone
- Outer Blingdenstone
- Inner Blingdenstone
- Rockblight
- Goldwhisker Warrens
- The Pudding Court
