### ISSUE TITLE
Walls - CoA

### ISSUE THREAD

**Issue by TheGiddyLimit** [TheGiddyLimit/plutonium-scenes#66]
Add walls for maps in `CoA`
- [ ] Avernus, the First Hell
- [ ] Avernus, the First Hell (Player Version)
- [x] Baazebul's Infernal Submersible
- [ ] Baazebul's Infernal Submersible (Player Version)
- [ ] Cania, the Eighth Hell
- [ ] Cania, the Eighth Hell (Player Version)
- [ ] Demon Nest (W3)
- [ ] Demon Nest (W3) (Player Version)
- [ ] Dis, the Second Hell
- [ ] Dis, the Second Hell (Player Version)
- [ ] Flow of the River Styx
- [ ] Flow of the River Styx (Player Version)
- [x] Koh Tam's Barge
- [ ] Koh Tam's Barge (Player Version)
- [ ] Maladomini, the Seventh Hell
- [ ] Maladomini, the Seventh Hell (Player Version)
- [ ] Malbolge, the Sixth Hell
- [ ] Malbolge, the Sixth Hell (Player Version)
- [ ] Minauros, the Third Hell
- [ ] Minauros, the Third Hell (Player Version)
- [ ] Nessus, the Ninth Hell
- [ ] Nessus, the Ninth Hell (Player Version)
- [ ] Phlegethos, the Fourth Hell
- [ ] Phlegethos, the Fourth Hell (Player Version)
- [ ] Ruined Tower (W2)
- [ ] Ruined Tower (W2) (Player Version)
- [ ] Stygia, the Fifth Hell
- [ ] Stygia, the Fifth Hell (Player Version)
- [ ] The Agora of Floating Knives
- [ ] The Agora of Floating Knives (Normal Map)
- [ ] The Agora of Floating Knives (Player Version)
- [x] The Brothers' Infernal Warship
- [ ] The Brothers' Infernal Warship (Player Version)
- [ ] The Chasm of Found Things
- [ ] The Chasm of Found Things (Player Version)
- [ ] The Elemental Preserve
- [ ] The Elemental Preserve (Infernal Map)
- [ ] The Elemental Preserve (Player Version)
- [ ] The Eye Market
- [ ] The Eye Market (Normal Map)
- [ ] The Eye Market (Player Version)
- [ ] The Ineffable Trove
- [ ] The Ineffable Trove (Infernal Map)
- [ ] The Ineffable Trove (Player Version)
- [ ] The Oasis of the Lethe
- [ ] The Oasis of the Lethe (Infernal Map)
- [ ] The Oasis of the Lethe (Player Version)
- [ ] The Sign of the Hag's Arms
- [ ] The Sign of the Hag's Arms (Player Version)
- [ ] The Sorrow Mine
- [ ] The Sorrow Mine (Player Version)
- [ ] The War-Slough
- [ ] The War-Slough (Infernal Map)
- [ ] The War-Slough (Player Version)

**Comment by revilowaldow** [comment]
Note this is only partially complete, the following maps are too low-resolution to be walled at this time. But if better assets become available they should be walled.

- Demon Nest (W3)
- Ruined Tower (W2)
- The Sign of the Hag's Arms
- The Sorrow Mine

**Comment by TheGiddyLimit** [comment]
the "HD" versions Roll20 has are only about ~double the res, which doesn't feel quite good enough for nice walling

ex:

![0](https://github.com/user-attachments/assets/e6d94923-af25-4381-b1e2-11165aabebe6)

thoughts?

**Comment by revilowaldow** [comment]
> doesn't feel quite good enough for nice walling
> thoughts?

Think I agree, it's still just a bit too small, think these can probably be skipped.
If someone objects then they're welcome to wall it themselves and contribute the data.
More generally, the art for CoA was just not available at the typical quality so not a lot can really be done.
