### ISSUE TITLE
Walls - SCAG

### ISSUE THREAD

**Issue by TheGiddyLimit** [TheGiddyLimit/plutonium-scenes#70]
Add walls for maps in `SCAG`

**Comment by revilowaldow** [comment]
No maps in SCAG require walls

**Comment by revilowaldow** [comment]
- [ ] Baldur's Gate–Map
- [ ] Darkhold–Map
- [ ] Evereska–Map
- [ ] Faerûn–Map
- [ ] Hartsvale–Map
- [ ] High Moor–Map
- [ ] Luskan–Map
- [ ] Mirabar–Map
- [ ] Nelanther–Map
- [ ] Neverwinter–Map
- [ ] Preface–Map
- [ ] Silverymoon–Map
- [ ] The Moonshaes–Map
- [ ] Trielta Hills–Map
- [ ] Waterdeep–Map
- [ ] Yartar–Map
