### ISSUE TITLE
Walls - TDCSR

### ISSUE THREAD

**Issue by TheGiddyLimit** [TheGiddyLimit/plutonium-scenes#71]
Add walls for maps in `TDCSR`

**Comment by revilowaldow** [comment]
No maps in TDCSR require walls.

**Comment by revilowaldow** [comment]
- [ ] Emon, The City of Fellowship
- [ ] Player Version
- [ ] Realm of Tal'Dorei
- [ ] Realm of Tal'Dorei—Large Watermarked
- [ ] Stilben
- [ ] The Alabaster Sierras
- [ ] The Bladeshimmer Shoreline
- [ ] The City of Kraghammer
- [ ] The City of Syngorn
- [ ] The City of Westruun
- [ ] The City of Whitestone
- [ ] The Cliffkeep Mountains
- [ ] The Dividing Plains
- [ ] The Lucidian Coast
- [ ] The Rifenmist Peninsula
- [ ] The Shearing Channel
- [ ] The Stormcrest Mountains
- [ ] The Verdant Expanse
